CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email CHARACTER VARYING(50) NOT NULL UNIQUE,
    password_hash CHARACTER VARYING(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);